alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: smartbot
    match:
      path:
        prefix: /
name: lionfish-app
region: ams
services:
- http_port: 8080
  image:
    deploy_on_push:
      enabled: true
    registry_type: DOCR
    repository: smartbot
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: smartbot
