# fly.toml file generated for smartbot on 2023-03-18T10:41:36+01:00

app = "smartbot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"
processes = ["smartbotweb"]

[build]
  builder = "paketobuildpacks/builder-jammy-full"
  buildpacks = ["paketo-buildpacks/dotnet-core"]

[build.args]
  BP_DOTNET_PROJECT_PATH="./src/Smartbot.Web"

[processes]
  smartbotweb = "dotnet ./Smartbot.Web.dll"

[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  PORT = 8080
[experimental]
  auto_rollback = true
[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["smartbotweb"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
