name: Fly Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ./source --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.SMARTBOT_FLY_API_TOKEN }}
